### ISSUE TITLE
[CI] Lighthouse

### ISSUE THREAD

**Issue by vitaliy-bobrov** [vitaliy-bobrov/js-rocks#46]
Add configuration in `.travis.yaml`:

```yaml
language: node_js
node_js:
  - 10 # use Node 10 LTS or later
before_install:
  - npm install -g @lhci/cli@0.3.x
script:
  - npm run build # build your site
  - lhci autorun # run lighthouse CI
addons:
  chrome: stable # make sure you have Chrome available
```
